name: AllInOne

on:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        cpp_compiler: [g++, clang++, cl]
        exclude:
          - os: ubuntu-latest
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.6.0'
        #arch: ${{ (matrix.os == 'windows-latest' && matrix.cpp_compiler == 'g++') && 'win64_mingw' || '' }}

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup C++ Compiler and Tools
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.cpp_compiler }}
        cmake: true
        ninja: true

    - name: Setup MSVC Developer Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
        vsversion: '2022'

    - name: Install LLVM (MSVC)
      id: llvm-install-msvc
      if: matrix.cpp_compiler == 'cl'
      shell: pwsh
      run: |
        choco install llvm --version=21.1.8 -y
        $llvmPath = "C:\Program Files\LLVM\lib\cmake\llvm"
        echo "LLVM_DIR=$llvmPath" >> "$GITHUB_OUTPUT"
        echo "CMAKE_PREFIX_PATH=$llvmPath" >> "$GITHUB_OUTPUT"

    - name: Install LLVM (Non-MSVC)
      id: llvm-install-non-msvc
      if: matrix.cpp_compiler != 'cl'
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "21.1.8"

    - name: Configure CMake (MSVC)
      if: matrix.cpp_compiler == 'cl'
      shell: pwsh
      run: |
        cmake -B "${{ steps.strings.outputs.build-output-dir }}"
          -G Ninja
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_PREFIX_PATH="${{ steps.llvm-install-msvc.outputs.CMAKE_PREFIX_PATH }}"
          -S "${{ github.workspace }}"

    - name: Configure CMake (Non-MSVC)
      if: matrix.cpp_compiler != 'cl'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -G Ninja
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_PREFIX_PATH="${{ steps.llvm-install-non-msvc.outputs.CMAKE_PREFIX_PATH }}"
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run Test (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./Tests/AllInOne/AllInOne.exe

    - name: Run Test (Linux)
      if: runner.os == 'Linux'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./Tests/AllInOne/AllInOne
